### Dodawanie nowego użytkownika
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "username": "exampleauth",
    "password": "password123",
    "email": "example@example.com",
    "name":"name",
    "surname":"surname"
}

### Logowanie użytkownika
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "password": "Password123@",
    "email": "tomasz@pl.pl"
}

### wylogowanie
POST http://localhost:3000/api/v1/auth/logout
Content-Type: application/json

### Wydłużenie tokenu
POST http://localhost:3000/api/v1/auth/refresh-token
Content-Type: application/json