
### Pobieranie użytkownika o id = 1
GET http://localhost:3000/api/v1/user/1
Content-Type: application/json

### Filter User
GET http://localhost:3000/api/v1/user?username=example
Content-Type: application/json

### Pobiera zaproszenia do chatu danego użytkownika
GET http://localhost:3000/api/v1/user/invitations
Content-Type: application/json

### Sprawdza czy użytkownik jest częścią danego chatu
GET http://localhost:3000/api/v1/conversation/isUser/66712888-cb0c-4b0e-a496-3e2536c881e5
Content-Type: application/json